-- require('user.rtp')
require('user.vars')
require('user.settings')
require('user.keymaps')
require('user.abbrev')
require('user.autocmd')
require('user.commands')
require('user.plugins')
require('user.telescope')
-- require('user.lsp')
